name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Make build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-build
        path: target/release/toxic_bot

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_LOGIN: ${{ secrets.DEPLOY_LOGIN }}
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: release-build
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.DEPLOY_HOST }}
      - name: ./deploy.sh
        run: exit 0
